FROM node:20-slim

WORKDIR /app

# Railway pasa las env vars como build args si se declaran con ARG
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_APPS_SCRIPT_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_APPS_SCRIPT_URL=$VITE_APPS_SCRIPT_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000
ENV PORT=3000

CMD ["node", "serve.js"]
